-- Footnote contract schema (SQLite). Source: PROJECT_SPEC.md §7, plus the additions accepted in Phase 0
-- (marked "+P0"; reasons in context/diagrams/architecture/README.md, "Schema gaps").
--
-- Conventions, relied on by both lanes:
--   * money is INTEGER cents in columns named *_cents. Tables are STRICT, so a fractional value is an error.
--   * ids are TEXT. World ids come from the seeder; everything else is generated by the writer.
--   * dates are 'YYYY-MM-DD'; timestamps are ISO-8601 UTC ('2026-07-31T23:59:59Z'); periods are 'YYYY-MM'.
--   * *_json columns hold JSON text validated by zod at the writer, not by SQLite.
--   * enum-like columns carry a CHECK only where the value set is frozen in src/contract/types.ts.
--
-- Changed only with both people in the conversation.

PRAGMA foreign_keys = ON;

-- ───────────────────────────── world and ledger ─────────────────────────────

-- +P0 party master: one id space for customers, vendors, employees and banks, so `party_id` means one thing
-- on trace, fact, bank_txn and Proposal. customer / vendor are extension rows keyed by the same id.
CREATE TABLE party (
  id              TEXT PRIMARY KEY,
  kind            TEXT NOT NULL CHECK (kind IN ('customer','vendor','employee','bank','internal','other')),
  name            TEXT NOT NULL,
  parent_party_id TEXT REFERENCES party(id),      -- parent pays for subsidiary
  status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_at      TEXT NOT NULL
) STRICT;

-- +P0 alias: every string a party is known by (bank descriptor, email domain, CRM name, legal name).
CREATE TABLE alias (
  id         TEXT PRIMARY KEY,
  party_id   TEXT NOT NULL REFERENCES party(id),
  alias      TEXT NOT NULL,
  alias_norm TEXT NOT NULL,                       -- lowercased, punctuation and suffixes stripped
  kind       TEXT NOT NULL CHECK (kind IN ('name','bank_descriptor','email_domain','email','external_id','other')),
  source     TEXT NOT NULL,                       -- 'seed' | 'learned' | connector name
  learned_from_decision_id TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (party_id, alias_norm, kind)
) STRICT;
CREATE INDEX alias_norm_idx ON alias(alias_norm);

CREATE TABLE customer (
  party_id           TEXT PRIMARY KEY REFERENCES party(id),
  payment_terms_days INTEGER NOT NULL DEFAULT 30,
  account_owner      TEXT,                        -- person to ask; resolves to a Slack user
  billing_email      TEXT,
  crm_external_id    TEXT
) STRICT;

CREATE TABLE vendor (
  party_id                 TEXT PRIMARY KEY REFERENCES party(id),
  payment_terms_days       INTEGER NOT NULL DEFAULT 30,
  default_expense_account  TEXT REFERENCES account(code),
  remit_email              TEXT,
  bank_details_hash        TEXT,                  -- hash of the remit-to account last verified
  bank_details_verified_at TEXT,
  bank_details_last_paid_hash TEXT                -- drift comparator: vendor bank details vs last paid
) STRICT;

-- chart of accounts. Core codes are constants in src/contract/accounts.ts and inserted by openDb().
CREATE TABLE account (
  code        TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  type        TEXT NOT NULL CHECK (type IN ('asset','liability','equity','revenue','expense')),
  control_for TEXT CHECK (control_for IN ('AR','AP'))   -- subledger this GL account must equal
) STRICT;

CREATE TABLE contract (
  id                TEXT PRIMARY KEY,
  customer_id       TEXT NOT NULL REFERENCES party(id),
  name              TEXT NOT NULL,
  start_date        TEXT NOT NULL,
  end_date          TEXT NOT NULL,                -- renewal date
  total_value_cents INTEGER NOT NULL,
  billing_frequency TEXT NOT NULL CHECK (billing_frequency IN ('monthly','quarterly','annual','one_time')),
  terms_json        TEXT NOT NULL DEFAULT '{}',   -- escalators, payment terms, extracted clauses
  trace_id          TEXT REFERENCES trace(id),    -- the contract file as evidence
  status            TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','expired','cancelled'))
) STRICT;

CREATE TABLE invoice (
  id           TEXT PRIMARY KEY,
  number       TEXT NOT NULL UNIQUE,              -- 'INV-1042'
  customer_id  TEXT NOT NULL REFERENCES party(id),
  contract_id  TEXT REFERENCES contract(id),
  issue_date   TEXT NOT NULL,
  due_date     TEXT NOT NULL,
  service_start TEXT,
  service_end   TEXT,
  amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0),
  open_cents   INTEGER NOT NULL CHECK (open_cents >= 0),
  status       TEXT NOT NULL CHECK (status IN ('open','partial','paid','void','disputed')),
  trace_id     TEXT REFERENCES trace(id),
  CHECK (open_cents <= amount_cents)
) STRICT;
CREATE INDEX invoice_customer_idx ON invoice(customer_id, status);

CREATE TABLE po (
  id           TEXT PRIMARY KEY,
  number       TEXT NOT NULL UNIQUE,
  vendor_id    TEXT NOT NULL REFERENCES party(id),
  date         TEXT NOT NULL,
  amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0),
  lines_json   TEXT NOT NULL DEFAULT '[]',        -- [{line_no, description, qty, unit_cents, amount_cents}]
  status       TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed','cancelled'))
) STRICT;

CREATE TABLE receipt (
  id           TEXT PRIMARY KEY,
  po_id        TEXT NOT NULL REFERENCES po(id),
  date         TEXT NOT NULL,
  amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0),
  lines_json   TEXT NOT NULL DEFAULT '[]'         -- [{po_line_no, qty}]
) STRICT;

CREATE TABLE bill (
  id             TEXT PRIMARY KEY,
  number         TEXT NOT NULL,                   -- vendor's invoice number; not unique on purpose (duplicates are planted)
  vendor_id      TEXT NOT NULL REFERENCES party(id),
  po_id          TEXT REFERENCES po(id),
  bill_date      TEXT NOT NULL,
  due_date       TEXT NOT NULL,
  received_date  TEXT NOT NULL,                   -- when it reached us (the 3 Aug cloud bill)
  service_start  TEXT,
  service_end    TEXT,
  amount_cents   INTEGER NOT NULL CHECK (amount_cents >= 0),
  open_cents     INTEGER NOT NULL CHECK (open_cents >= 0),
  status         TEXT NOT NULL CHECK (status IN ('received','held','approved','scheduled','paid','void')),
  obligation_key TEXT,                            -- +P0 vendor | PO line or service period | amount; duplicate block
  requested_by   TEXT,                            -- audit: self-approved request
  approved_by    TEXT,
  trace_id       TEXT REFERENCES trace(id),
  CHECK (open_cents <= amount_cents)
) STRICT;
CREATE INDEX bill_vendor_idx ON bill(vendor_id, status);
CREATE INDEX bill_obligation_idx ON bill(obligation_key);

CREATE TABLE bank_txn (
  id               TEXT PRIMARY KEY,
  bank_account     TEXT NOT NULL DEFAULT 'operating',
  date             TEXT NOT NULL,                 -- posted date on the statement
  amount_cents     INTEGER NOT NULL,              -- signed: + money in, - money out
  description      TEXT NOT NULL,                 -- thin, as the bank prints it
  kind             TEXT NOT NULL CHECK (kind IN ('ach','wire','check','card','fee','payroll','payout','transfer','other')),
  party_id         TEXT REFERENCES party(id),     -- null until resolved through alias
  status           TEXT NOT NULL DEFAULT 'unmatched' CHECK (status IN ('unmatched','matched','reconciling_item','excluded')),
  source           TEXT NOT NULL DEFAULT 'bank_file' CHECK (source IN ('bank_file','payout_file')),
  external_id      TEXT NOT NULL,
  trace_id         TEXT REFERENCES trace(id),
  UNIQUE (source, external_id)
) STRICT;
CREATE INDEX bank_txn_status_idx ON bank_txn(status, date);

CREATE TABLE payroll_run (
  id            TEXT PRIMARY KEY,
  period        TEXT NOT NULL,
  pay_date      TEXT NOT NULL,
  gross_cents   INTEGER NOT NULL,
  taxes_cents   INTEGER NOT NULL,
  net_cents     INTEGER NOT NULL,
  register_json TEXT NOT NULL DEFAULT '[]'
) STRICT;

CREATE TABLE period (
  id         TEXT PRIMARY KEY,                    -- 'YYYY-MM'
  status     TEXT NOT NULL CHECK (status IN ('open','closing','locked')),
  closed_by  TEXT NOT NULL DEFAULT 'agent' CHECK (closed_by IN ('human','agent')),  -- Q2 is human-closed history
  locked_at  TEXT,                                -- +P0
  locked_by  TEXT
) STRICT;

CREATE TABLE gl_entry (
  id                 TEXT PRIMARY KEY,
  period             TEXT NOT NULL REFERENCES period(id),
  date               TEXT NOT NULL,
  source_decision_id TEXT REFERENCES decision(id),     -- null only for seeded history
  memo               TEXT NOT NULL,
  posted_at          TEXT NOT NULL,               -- +P0 wall clock of the post; date is the accounting date
  posted_by          TEXT NOT NULL,               -- 'seed' | 'runtime'
  reversal_mode      TEXT NOT NULL DEFAULT 'none' -- +P0 accruals only
                     CHECK (reversal_mode IN ('none','auto_next_period','on_bill_arrival','accumulate_true_up')),
  reverses_entry_id  TEXT REFERENCES gl_entry(id)
) STRICT;
CREATE INDEX gl_entry_period_idx ON gl_entry(period);

CREATE TABLE gl_line (
  entry_id     TEXT NOT NULL REFERENCES gl_entry(id),
  line_no      INTEGER NOT NULL,
  account      TEXT NOT NULL REFERENCES account(code),
  debit_cents  INTEGER NOT NULL DEFAULT 0 CHECK (debit_cents >= 0),
  credit_cents INTEGER NOT NULL DEFAULT 0 CHECK (credit_cents >= 0),
  customer_id  TEXT REFERENCES party(id),
  vendor_id    TEXT REFERENCES party(id),
  memo         TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (entry_id, line_no),
  CHECK ((debit_cents = 0) <> (credit_cents = 0)) -- exactly one side is non-zero
) STRICT;
CREATE INDEX gl_line_account_idx ON gl_line(account);

-- +P0 application: which document a cash movement or credit was applied to. Subledger balances and
-- "every bank line matched exactly once" are computed from here.
CREATE TABLE application (
  id           TEXT PRIMARY KEY,
  decision_id  TEXT REFERENCES decision(id),      -- null only for seeded history
  entry_id     TEXT REFERENCES gl_entry(id),
  bank_txn_id  TEXT REFERENCES bank_txn(id),      -- null for a credit memo or write-off
  doc_kind     TEXT NOT NULL CHECK (doc_kind IN ('invoice','bill')),
  doc_id       TEXT NOT NULL,
  amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
  kind         TEXT NOT NULL CHECK (kind IN ('payment','credit_memo','write_off','customer_credit')),
  applied_at   TEXT NOT NULL,
  unwound_at   TEXT
) STRICT;
CREATE INDEX application_doc_idx ON application(doc_kind, doc_id);
CREATE INDEX application_bank_idx ON application(bank_txn_id);

-- +P0 schedule: one engine for revenue, prepaid amortisation and stock comp. A revision never edits a
-- schedule; it writes a new version and points the old one at it (prospective, double-hit guard).
CREATE TABLE schedule (
  id                 TEXT PRIMARY KEY,
  kind               TEXT NOT NULL CHECK (kind IN ('revenue','prepaid','stock_comp')),
  source_ref         TEXT NOT NULL,               -- contract.id | bill.id | grant id
  party_id           TEXT REFERENCES party(id),
  version            INTEGER NOT NULL DEFAULT 1,
  total_cents        INTEGER NOT NULL,
  start_date         TEXT NOT NULL,
  end_date           TEXT NOT NULL,
  as_of              TEXT NOT NULL,
  superseded_by_id   TEXT REFERENCES schedule(id),
  reason_decision_id TEXT REFERENCES decision(id),
  UNIQUE (kind, source_ref, version)
) STRICT;

CREATE TABLE schedule_line (
  schedule_id  TEXT NOT NULL REFERENCES schedule(id),
  period       TEXT NOT NULL,
  amount_cents INTEGER NOT NULL,
  entry_id     TEXT REFERENCES gl_entry(id),      -- set once recognised
  PRIMARY KEY (schedule_id, period)
) STRICT;

-- ───────────────────────────── shared judgment layer ─────────────────────────────

-- Three clocks (+P0): event_time = when it happened in the world; recorded_time = when the world's system
-- recorded it (supplied by the seeder; the no-look-ahead guard in replay reads this one); ingested_at = when
-- we pulled it (always tonight for seeded data, never used for as-of).
CREATE TABLE trace (
  id                  TEXT PRIMARY KEY,
  source              TEXT NOT NULL,              -- TRACE_SOURCES in src/contract/types.ts
  kind                TEXT NOT NULL,              -- 'email' | 'chat_message' | 'bank_line' | 'contract' | ...
  external_id         TEXT NOT NULL,
  event_time          TEXT NOT NULL,
  recorded_time       TEXT NOT NULL,
  ingested_at         TEXT NOT NULL,              -- +P0
  party_id            TEXT REFERENCES party(id),
  content_hash        TEXT NOT NULL,              -- +P0 sha256 of payload_json; evidence versioning
  version             INTEGER NOT NULL DEFAULT 1, -- +P0
  supersedes_trace_id TEXT REFERENCES trace(id),  -- +P0
  payload_json        TEXT NOT NULL,
  UNIQUE (source, external_id, version)           -- ingestion idempotency key
) STRICT;
CREATE INDEX trace_party_idx ON trace(party_id, recorded_time);
CREATE INDEX trace_recorded_idx ON trace(recorded_time);

CREATE TABLE decision_point (
  id                 TEXT PRIMARY KEY,
  function           TEXT NOT NULL,
  period             TEXT NOT NULL,
  kind               TEXT NOT NULL,
  trace_ids_json     TEXT NOT NULL DEFAULT '[]',
  human_outcome_json TEXT,                        -- never reachable from agent tools
  decided_at         TEXT NOT NULL
) STRICT;

CREATE TABLE intent (
  id                 TEXT PRIMARY KEY,
  parent_id          TEXT REFERENCES intent(id),
  function           TEXT NOT NULL,
  question           TEXT NOT NULL,
  owner              TEXT NOT NULL,
  status             TEXT NOT NULL CHECK (status IN ('open','in_progress','parked','closed','cancelled')),
  end_condition_json TEXT NOT NULL DEFAULT '{}',
  dedupe_key         TEXT,                        -- +P0 drift monitor: same drift updates the intent, never reopens it
  created_at         TEXT NOT NULL,
  closed_at          TEXT
) STRICT;
CREATE UNIQUE INDEX intent_dedupe_idx ON intent(dedupe_key) WHERE dedupe_key IS NOT NULL AND status NOT IN ('closed','cancelled');

CREATE TABLE decision (
  id                TEXT PRIMARY KEY,
  intent_id         TEXT REFERENCES intent(id),
  function          TEXT NOT NULL,
  mode              TEXT NOT NULL CHECK (mode IN ('live','replay','shadow')),
  decision_point_id TEXT REFERENCES decision_point(id),
  kind              TEXT NOT NULL,
  proposal_json     TEXT NOT NULL,
  actor             TEXT NOT NULL,                -- 'policy:<id>' | 'fact:<id>' | model id
  autonomy_level    TEXT NOT NULL CHECK (autonomy_level IN ('shadow','review','auto')),
  route             TEXT CHECK (route IN ('AUTO','PROPOSE','ESCALATE','REFUSE','BLOCK')),  -- +P0 what the eval scores
  status            TEXT NOT NULL DEFAULT 'proposed'                                       -- +P0
                    CHECK (status IN ('proposed','kernel_rejected','awaiting_approval','awaiting_answer','posted','refused','blocked','unwound')),
  model_calls       INTEGER NOT NULL DEFAULT 0,
  cost_micros       INTEGER NOT NULL DEFAULT 0,
  created_at        TEXT NOT NULL,
  posted_at         TEXT                          -- +P0
) STRICT;
CREATE INDEX decision_intent_idx ON decision(intent_id);

CREATE TABLE workpaper (
  id             TEXT PRIMARY KEY,
  decision_id    TEXT NOT NULL REFERENCES decision(id),
  marks_json     TEXT NOT NULL,                   -- Mark[]
  kernel_verdict TEXT NOT NULL CHECK (kernel_verdict IN ('accept','reject')),
  checkable_num  INTEGER NOT NULL,
  checkable_den  INTEGER NOT NULL,
  stage          TEXT NOT NULL DEFAULT 'proposal' CHECK (stage IN ('proposal','post_gate')),  -- +P0 the kernel runs twice
  created_at     TEXT NOT NULL
) STRICT;

-- +P0 approval: the approval is a checked artifact. Decision 2026-09-19: a model controller is a reviewer;
-- only a human (directly, or in advance through a fact's authority ceiling) is an approver.
CREATE TABLE approval (
  id                      TEXT PRIMARY KEY,
  decision_id             TEXT NOT NULL REFERENCES decision(id),
  role                    TEXT NOT NULL CHECK (role IN ('reviewer','approver')),
  actor                   TEXT NOT NULL,          -- Slack user id, or the controller's model id
  actor_kind              TEXT NOT NULL CHECK (actor_kind IN ('human','model')),
  disposition             TEXT NOT NULL CHECK (disposition IN ('approved','rejected','changes_requested')),
  authority_ceiling_cents INTEGER,                -- from the approval matrix, at the time of approval
  via_fact_id             TEXT REFERENCES fact(id),     -- approval given in advance through a scoped fact
  via_policy_id           TEXT REFERENCES policy(id),
  channel                 TEXT NOT NULL CHECK (channel IN ('slack','console','api','precedent')),
  note                    TEXT,
  created_at              TEXT NOT NULL,
  CHECK (role = 'reviewer' OR actor_kind = 'human')
) STRICT;
CREATE INDEX approval_decision_idx ON approval(decision_id);

-- +P0 blocked_attempt: a BLOCK is persisted, and an approval does not lift it. Only a recorded out-of-band
-- verification by a second person does (B-17 changed bank details).
CREATE TABLE blocked_attempt (
  id             TEXT PRIMARY KEY,
  decision_id    TEXT REFERENCES decision(id),
  intent_id      TEXT REFERENCES intent(id),
  function       TEXT NOT NULL,
  rule           TEXT NOT NULL,                   -- kernel check or engine rule that fired
  reason         TEXT NOT NULL,
  subject_ref    TEXT,                            -- bill id, vendor id, obligation key...
  proposal_json  TEXT,
  actor          TEXT NOT NULL,
  created_at     TEXT NOT NULL,
  lift_condition TEXT,
  lifted_at      TEXT,
  lifted_by      TEXT,
  verified_by    TEXT,                            -- second person; must differ from lifted_by
  CHECK (lifted_by IS NULL OR verified_by IS NULL OR lifted_by <> verified_by)
) STRICT;

CREATE TABLE artifact (
  id          TEXT PRIMARY KEY,
  decision_id TEXT REFERENCES decision(id),
  intent_id   TEXT REFERENCES intent(id),
  function    TEXT NOT NULL,
  system      TEXT NOT NULL,                      -- 'ledger' | 'quickbooks' | 'slack' | 'gmail' | 'console' | ...
  external_id TEXT NOT NULL,
  kind        TEXT NOT NULL,
  amount_cents INTEGER,                           -- +P0 ripple view: the same amounts in every function
  created_at  TEXT NOT NULL,
  unwound_at  TEXT
) STRICT;
CREATE INDEX artifact_intent_idx ON artifact(intent_id);

CREATE TABLE fact (
  id                      TEXT PRIMARY KEY,
  party_id                TEXT REFERENCES party(id),
  predicate               TEXT NOT NULL,
  value_json              TEXT NOT NULL,
  scope_json              TEXT NOT NULL DEFAULT '{}',
  valid_from              TEXT NOT NULL,
  valid_to                TEXT,
  learned_at              TEXT NOT NULL,
  source_trace_ids_json   TEXT NOT NULL DEFAULT '[]',
  stated_by               TEXT,
  approved_by             TEXT,
  authority_ceiling_cents INTEGER,                -- +P0 largest single entry this fact pre-approves (AUTO above $500 needs it)
  explained_amount_cents  INTEGER,                -- +P0 a fact suppresses only the drift it explains
  status                  TEXT NOT NULL CHECK (status IN ('candidate','active','superseded','expired','rejected'))
) STRICT;
CREATE INDEX fact_party_idx ON fact(party_id, predicate, status);

CREATE TABLE policy (
  id             TEXT PRIMARY KEY,
  function       TEXT NOT NULL,
  name           TEXT NOT NULL,
  condition_json TEXT NOT NULL,
  action_json    TEXT NOT NULL,
  intent_text    TEXT NOT NULL,
  tier           TEXT NOT NULL,                   -- portability tier
  backtest_json  TEXT NOT NULL DEFAULT '{}',
  status         TEXT NOT NULL CHECK (status IN ('proposed','approved','rejected','retired')),
  approved_by    TEXT,
  approved_at    TEXT
) STRICT;

CREATE TABLE replay_result (
  decision_point_id TEXT NOT NULL REFERENCES decision_point(id),
  decision_id       TEXT NOT NULL REFERENCES decision(id),
  agrees            INTEGER NOT NULL CHECK (agrees IN (0,1)),
  diff_json         TEXT NOT NULL DEFAULT '{}',
  triage            TEXT,
  PRIMARY KEY (decision_point_id, decision_id)
) STRICT;

CREATE TABLE escalation (
  id            TEXT PRIMARY KEY,
  decision_id   TEXT REFERENCES decision(id),
  intent_id     TEXT REFERENCES intent(id),       -- +P0 an escalation can precede any decision
  asked_user    TEXT NOT NULL,
  question_json TEXT NOT NULL,
  answer_json   TEXT,
  dedupe_key    TEXT,                             -- +P0 party | predicate | decision kind: never asked twice
  asked_at      TEXT NOT NULL,
  answered_at   TEXT,
  slack_ts      TEXT
) STRICT;
CREATE INDEX escalation_dedupe_idx ON escalation(dedupe_key);

-- ───────────────────────────── coordination ─────────────────────────────

CREATE TABLE event (
  id            INTEGER PRIMARY KEY AUTOINCREMENT, -- bus order
  ts            TEXT NOT NULL,
  topic         TEXT NOT NULL,                    -- TOPICS in src/contract/topics.ts
  from_function TEXT NOT NULL,
  intent_id     TEXT REFERENCES intent(id),
  payload_json  TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE INDEX event_topic_idx ON event(topic, id);

-- +P0 one cursor per subscriber, so a restarted process resumes instead of replaying the bus.
CREATE TABLE event_cursor (
  subscriber    TEXT PRIMARY KEY,
  last_event_id INTEGER NOT NULL DEFAULT 0
) STRICT;

CREATE TABLE checklist_item (
  id                TEXT PRIMARY KEY,
  period            TEXT NOT NULL REFERENCES period(id),
  function          TEXT NOT NULL,
  name              TEXT NOT NULL,
  depends_on_json   TEXT NOT NULL DEFAULT '[]',
  status            TEXT NOT NULL CHECK (status IN ('pending','in_progress','blocked','done','n_a')),
  blocked_reason    TEXT,
  decision_ids_json TEXT NOT NULL DEFAULT '[]',
  UNIQUE (period, name)
) STRICT;

CREATE TABLE forecast_line (
  id           TEXT PRIMARY KEY,
  as_of        TEXT NOT NULL,                     -- forecast version
  week         TEXT NOT NULL,                     -- Monday of the week, 'YYYY-MM-DD'
  kind         TEXT NOT NULL,                     -- 'opening_cash' | 'ar_receipt' | 'ap_payment' | 'payroll' | ...
  source_ref   TEXT,
  amount_cents INTEGER NOT NULL,                  -- signed
  fact_id      TEXT REFERENCES fact(id)
) STRICT;
CREATE INDEX forecast_asof_idx ON forecast_line(as_of, week);

CREATE TABLE forecast_miss (
  id             TEXT PRIMARY KEY,
  week           TEXT NOT NULL,
  expected_cents INTEGER NOT NULL,
  actual_cents   INTEGER NOT NULL,
  decision_id    TEXT REFERENCES decision(id)
) STRICT;

-- +P0 seeder manifest: world id -> external id per system. Makes seeding idempotent and --reset possible.
CREATE TABLE seed_manifest (
  world_id    TEXT NOT NULL,
  system      TEXT NOT NULL,                      -- 'local' | 'quickbooks' | 'hubspot' | 'gmail' | 'slack'
  kind        TEXT NOT NULL,
  external_id TEXT NOT NULL,
  seeded_at   TEXT NOT NULL,
  PRIMARY KEY (world_id, system)
) STRICT;
