/** Event topics: the 50 in context/diagrams/architecture/EVENT_TOPICS.md. Naming rule: function.object.verb_past. */
export const TOPICS = [
  "ingest.committed",
  "ingest.refused",
  "evidence.reversioned",
  "board.consent_ingested",
  "crm.deal.closed_won",
  "hr.departure_detected",
  "drift.explained",
  "drift.logged_immaterial",
  "drift.updated",
  "human.escalation.opened",
  "human.escalation.answered",
  "fact.activated",
  "entry.posted",
  "entry.blocked",
  "ar.credit_memo.posted",
  "ar.payment.applied",
  "ar.dispute.opened",
  "ar.unapplied_cash",
  "ar.receivable.reopened",
  "ap.bill.approved",
  "ap.bill.held",
  "ap.payment.scheduled",
  "ap.vendor.change_requested",
  "bankrec.unmatched",
  "bankrec.reversal_detected",
  "bankrec.reconciled",
  "bankrec.stale",
  "rev.schedule.revised",
  "rev.recognised",
  "rev.leakage.found",
  "rev.invoice_issued",
  "billing.expectation.changed",
  "close.accrual.posted",
  "close.tb.final",
  "close.period.locked",
  "close.out_of_period",
  "forecast.updated",
  "forecast.miss.classified",
  "forecast.min_cash.breach",
  "report.flux.cleared",
  "report.flux.unexplained",
  "report.pack.published",
  "audit.finding.raised",
  "audit.pack.ready",
  "audit.evidence.invalidated",
  "equity.forfeiture",
  "equity.expense_revised",
  "equity.exercise_expected",
  "equity.nso_exercise",
  "equity.compliance_flag",
] as const;

export type Topic = (typeof TOPICS)[number];
