import { mkdtempSync, rmSync } from "node:fs";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { AddressInfo } from "node:net";
import { expect, it } from "vitest";
import { buildConnectors } from "../../src/connectors/index.js";
import { driftOnce } from "../../src/drift/monitor.js";
import { ingestAll } from "../../src/ingest/ingest.js";
import { openWorldDb } from "../../src/ledger/db.js";
import { applicableFacts } from "../../src/memory/applicability.js";
import { APP_CONFIG } from "../../src/packs/index.js";
import { readControlTotals } from "../../src/runtime/kernelContext.js";
import { proposeEntry } from "../../src/runtime/proposeEntry.js";
import { generateGlobalJuly } from "../../src/seed/globalJuly.js";
import { seedLocal, writeStores } from "../../src/seed/local.js";
import { handle } from "../app.js";

// This exercises the real HTTP actions, source ingestion and downstream engines. The disputed proposal is
// explicitly supplied by the test, not presented as a live model result. Live investigation is a separate check.
it("presentation: sources → learned fee rule → FX split → rejected draft → hold → decision → next invoice → audit", async () => {
  const dir = mkdtempSync(join(tmpdir(), "presentation-e2e-"));
  const db = openWorldDb(join(dir, "month.db"));
  const stores = join(dir, "stores");
  const server = createServer((req, res) => void handle(db, stores, false, req, res));
  try {
    const { world } = generateGlobalJuly();
    seedLocal(db, world);
    writeStores(world, stores);
    const connectors = await buildConnectors(new Set(), stores);
    const first = await ingestAll(db, connectors);
    expect(Object.values(first).some(r => "error" in r)).toBe(false);
    const second = await ingestAll(db, connectors);
    expect(Object.values(second).every(r => "committed" in r && r.committed === 0)).toBe(true);
    await driftOnce(db);
    await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
    const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
    expect((await (await fetch(`${base}/api/overview`)).json()).read_only).toBe(false);
    const post = async (action: string, body: unknown = {}): Promise<any> => {
      const res = await fetch(`${base}/api/do/${action}`, { method: "POST", headers: { "Content-Type": "application/json", origin: base }, body: JSON.stringify(body) });
      const result = await res.json();
      expect([action, res.status, result.error]).toEqual([action, 200, undefined]);
      return result;
    };
    const main = db.prepare("SELECT id, case_json FROM intent WHERE json_extract(case_json, '$.bank_txn_id') = 'BTX-320'").get() as { id: string; case_json: string };
    const addon = db.prepare("SELECT id FROM intent WHERE json_extract(case_json, '$.bank_txn_id') = 'BTX-321'").get() as { id: string };
    const balance = (id: string) => (db.prepare("SELECT open_cents FROM invoice WHERE id = ?").get(id) as { open_cents: number }).open_cents;
    const learned = await post("learn");
    const draft = learned.drafts.find((d: any) => d.policy_id);
    expect(draft).toBeDefined();
    await post("policy", { policy_id: draft.policy_id, as: "U_CTRL" });
    await post("run");
    expect(balance("INV-3201")).toBe(220000);
    expect(balance("INV-3202")).toBe(55000);
    const posted = db.prepare("SELECT kind FROM decision WHERE intent_id = ? AND posted_at IS NOT NULL ORDER BY rowid").all(main.id);
    expect(posted).toEqual([{ kind: "apply_payment" }, { kind: "write_off" }, { kind: "fx_realized" }]);
    const c = JSON.parse(main.case_json);
    const deps = { config: APP_CONFIG };
    const meta = { actor: "test:scripted-investigator", mode: "live" as const, autonomy_level: "review" as const, tier: 1, bound_intent_id: main.id };
    const hold = { intent_id: main.id, function: "ar", kind: "dispute_hold", party_id: "vossberg", entry_date: "2026-07-15", applications: [{ doc_id: "INV-3201", amount_cents: 220000 }], entries: [], evidence: [{ claim: "bank evidence for the receipt", trace_id: c.trace_ids[0] }], policy_refs: [], fact_refs: [], judgment: [] };
    const wrong = proposeEntry(db, { ...hold, entries: [{ account: "2400", debit_cents: 220000, credit_cents: 0, memo: "wrong: a hold must not book a credit" }, { account: "1200", debit_cents: 0, credit_cents: 220000, memo: "wrong" }] }, meta, deps);
    expect(wrong.status).toBe("rejected");
    expect(balance("INV-3201")).toBe(220000);
    const held = proposeEntry(db, hold, meta, deps);
    expect(held.status).toBe("pending_approval");
    if (held.status !== "pending_approval") throw new Error("Expected a held decision");
    const decided = await post("decide", { decision_id: held.decision_id, as: "U_CFO", treatment: "credit_memo", uses: "standing", valid_to: "2026-09-30", pct_off: 2, text: "Approve a standing 2% credit for Vossberg through September for the June outage." });
    expect(decided).toMatchObject({ status: "answered", fact_status: "active" });
    expect((await post("approve", { decision_id: decided.proposal.decision_id, as: "U_CTRL", outcome: "approved" })).status).toBe("posted");
    expect(balance("INV-3201")).toBe(0);
    const questions = () => (db.prepare("SELECT COUNT(*) AS n FROM escalation").get() as { n: number }).n;
    const questionsBefore = questions();
    await post("run", { intent_id: addon.id });
    const credit = db.prepare("SELECT id, proposal_json FROM decision WHERE intent_id = ? AND kind = 'credit_memo' AND posted_at IS NULL ORDER BY rowid DESC LIMIT 1").get(addon.id) as { id: string; proposal_json: string };
    expect(credit).toBeDefined();
    expect(JSON.parse(credit.proposal_json)).toMatchObject({ fact_refs: [decided.fact_id], applications: [{ doc_id: "INV-3202", amount_cents: 55000 }] });
    expect(questions()).toBe(questionsBefore);
    expect(applicableFacts(db, { party_id: "brightwater", kind: "credit_memo", entry_date: "2026-07-22", amount_cents: 55000 }).applicable).toEqual([]);
    expect(applicableFacts(db, { party_id: "vossberg", kind: "credit_memo", entry_date: "2026-10-01", amount_cents: 55000 }).applicable).toEqual([]);
    await post("approve", { decision_id: credit.id, as: "U_CTRL", outcome: "approved" });
    expect(balance("INV-3202")).toBe(0);
    const entries = () => (db.prepare("SELECT COUNT(*) AS n FROM gl_entry").get() as { n: number }).n;
    const entriesBefore = entries();
    await post("run", { intent_id: main.id });
    await post("run", { intent_id: addon.id });
    expect(entries()).toBe(entriesBefore);
    expect(questions()).toBe(questionsBefore);
    const totals = readControlTotals(db);
    expect(totals.ar_gl_cents).toBe(totals.ar_subledger_cents);
    expect((db.prepare("SELECT COUNT(*) AS n FROM ripple WHERE intent_id = ?").get(main.id) as { n: number }).n).toBeGreaterThan(0);
    const beforeAudit = db.prepare("SELECT id, content_hash, payload_json FROM trace ORDER BY id").all();
    const audit = await post("audit", { period: "2026-07", tamper: true });
    expect(audit.summary.findings_total).toBe(0);
    expect(audit.tampered.summary.findings_total).toBeGreaterThan(0);
    expect(db.prepare("SELECT id, content_hash, payload_json FROM trace ORDER BY id").all()).toEqual(beforeAudit);
  } finally {
    await new Promise<void>(resolve => server.close(() => resolve()));
    db.close();
    rmSync(dir, { recursive: true, force: true });
  }
}, 60_000);
